language: go
matrix:
  include:
    - go: 1.7.x
    - go: 1.8.x
    - go: 1.9.x
    - go: 1.10.x
    - go: 1.11.x
    - go: 1.12.x
    - go: tip
  allow_failures:
    - go: tip

env:
  global:
    - GOFMT_VERSION=1.12

before_install:
  - curl https://glide.sh/get | sh

install:
  - glide install

script:
 - ./test

notifications:
  email: false

sudo: false
