language: go
matrix:
  include:
    - go: 1.7.x
    - go: 1.8.x
    - go: 1.9.x
    - go: 1.10.x
    - go: tip
  allow_failures:
    - go: tip

script:
 - ./test

notifications:
  email: false

sudo: false
